# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewsApp
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod "PromiseKit"
  pod ‘FirebaseUI'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'

end
